openapi: 3.0.3
info:
  title: OpenAPI schema for template terraform-kubernetes-kafka
components:
  schemas:
    variables:
      required: []
      type: object
      properties:
        context:
          title: Context
          type: object
          description: |
            Receive contextual information. When Walrus deploys, Walrus will inject specific contextual information into this field.

            Examples:
            ```
            context:
              project:
                name: string
                id: string
              environment:
                name: string
                id: string
              resource:
                name: string
                id: string
            ```
          default: {}
          additionalProperties:
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            hidden: true
            order: 1
        infrastructure:
          title: Infrastructure
          type: object
          description: |
            Specify the infrastructure information for deploying.

            Examples:
            ```
            infrastructure:
              namespace: string, optional
              image_registry: string, optional
              domain_suffix: string, optional
            ```
          default: {}
          properties:
            domain_suffix:
              description: |
                Specify the domain name of the Kubernetes cluster.
              title: Domain Suffix
              type: string
              x-walrus-ui:
                order: 3
            image_registry:
              description: |
                Specify the image registry to pull the bitnami/kafka image, default is `registry-1.docker.io`.
              title: Image Registry
              type: string
              x-walrus-ui:
                order: 2
            namespace:
              title: Namespace
              type: string
              x-walrus-ui:
                hidden: true
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 2
        engine_version:
          title: Engine Version
          type: string
          description: |
            Specify the deployment engine version, select from https://hub.docker.com/r/bitnami/kafka/tags.
          default: "3.6"
          x-walrus-ui:
            group: Basic
            order: 3
        username:
          title: Username
          type: string
          description: |
            Specify the account username.
          default: user
          x-walrus-ui:
            group: Basic
            order: 4
        password:
          title: Password
          type: string
          description: |
            Specify the account password. If not specified, it will generate a random password.
          x-walrus-ui:
            group: Basic
            order: 5
        resources:
          title: Resources
          type: object
          description: |
            Specify the computing resources.

            Examples:
            ```
            resources:
              cpu: number, optional
              memory: number, optioanl       # in megabyte
            ```
          default:
            cpu: 0.25
            memory: 256
          required:
          - cpu
          - memory
          properties:
            cpu:
              description: |
                Specify the cpu resources. Unit is core.
              title: Cpu(Core)
              type: number
              x-walrus-ui:
                order: 1
            memory:
              description: |
                Specify the memory resources. Unit is megabyte.
              title: Memory(MiB)
              type: number
              x-walrus-ui:
                order: 2
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 6
        storage:
          title: Storage
          type: object
          description: |
            Specify the storage resources.

            Examples:
            ```
            storage:                         # convert to empty_dir volume or dynamic volume claim template
              class: string, optional
              size: number, optional         # in megabyte
            ```
          properties:
            class:
              description: |
                Specify the storage class. If not specified, it will use the default provisioner.
              title: Class
              type: string
              x-walrus-ui:
                order: 1
            size:
              description: |
                Specify the storage size. Unit is megabyte.
              default: 20480
              title: Size(MiB)
              type: number
              x-walrus-ui:
                order: 2
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 7
        seeding:
          title: Seeding
          type: object
          description: |
            Specify the configuration to kafka provisioning.

            Examples:
            ```
            seeding:
                topics: list(string), optional
                partitions: number, optional
                replication_factor: number, optional
            ```
          default: {}
          properties:
            partitions:
              description: |
                Specify the parition number of the seeding topic.
              title: Partitions
              type: number
              x-walrus-ui:
                order: 2
            replication_factor:
              description: |
                Specify the replication factor of the seeding topic.
              title: Replicas
              type: number
              x-walrus-ui:
                order: 3
            topics:
              description: |
                Specify the seeding topics.
              items:
                type: string
              title: Topics
              type: array
              x-walrus-ui:
                colSpan: 12
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 8
